name: Docker Check

on:
  pull_request:
    branches:
      - main

jobs:
  docker-check:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Levantar contenedores
        run: docker compose up -d --build

      - name: Esperar contenedores
        run: sleep 20

      - name: Verificar estado de contenedores
        run: |
          docker compose ps

          BACKEND_STATUS=$(docker inspect -f '{{.State.Running}}' Backend)
          DATABASE_STATUS=$(docker inspect -f '{{.State.Running}}' Database)

          if [ "$BACKEND_STATUS" != "true" ]; then
            echo "El contenedor Backend no está corriendo"
            docker compose logs Backend
            exit 1
          fi

          if [ "$DATABASE_STATUS" != "true" ]; then
            echo "El contenedor Database no está corriendo"
            docker compose logs Database
            exit 1
          fi

          echo "Backend y Database están corriendo correctamente"

      - name: Apagar contenedores
        if: always()
        run: docker compose down -v